author:
- given: Neil D.
  family: Lawrence
  institution: University of Cambridge
  gscholar: r3SJcvoAAAAJ
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
layout: lecture
venue: Virtual (Zoom)
postsdir: ../../../mlatcl/r250/_lectures/
slidesdir: ../../../mlatcl/r250/slides/
notesdir: ../../../mlatcl/r250/_notes/
notebooksdir: ../../../mlatcl/r250/_notebooks/
writediagramsdir: .
diagramsdir: ./slides/diagrams/
transition: None
ghub:
- organization: lawrennd
  repository: talks
  branch: gh-pages
  directory: _r250
